name: CI
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm list --depth=0  # للتحقق من التثبيت
      - run: npm run test
